### ISSUE TITLE
Color of T°

### ISSUE THREAD

**Issue by Doudy** [M-Arvidsson/MMM-domoticz#2]
Hello,
Is it possible to change the color according to the T ° as in domoticz ?

**Comment by Doudy** [comment]
Nobody ?

**Comment by macbenoit** [comment]
Look at the css

**Comment by Doudy** [comment]
> Look at the css

@ macbenoit
Thank you for your answer but it takes a lot of people to make a very big effort to evolve.
I want to go see in the css but what to do after?

**Comment by Doudy** [comment]
nobody ?

**Comment by Doudy** [comment]
nobody ?

**Comment by Doudy** [comment]
Hello nobody ?
